Feature/1010 学習記録のコピー生成を追加
hachioji-sakura/lms pull request #1020
Opened 2021-06-01 07:37 UTC by ShotaKasaiGit

#1010 のプルリク になります

2021-06-02 07:09 UTC, osuke0208 requested changes
レビューしました。
修正をお願いします。

2021-06-02 07:09 UTC, osuke0208 commented on resources/views/tasks/create.blade.php
> +            <textarea name="title" id="title" class="form-control" placeholder="{{__('messages.task_body_placeholder')}}" required="true"  maxlength=1000 >{{isset($item) ? $item->full_title : ''}}</t
request()->has('copy_id')のときに"(コピー)"と先頭につけるようにしてください。

2021-06-02 07:09 UTC, osuke0208 commented on resources/views/tasks/components/buttons.blade.php
> +    <a href="javascript:void(0)" title="{{__('labels.copy_button')}}" page_form="dialog" page_title="{{$item->title}}" page_url="/tasks/create?copy_id={{$item->id}}&student_id={{$student->id}}" class
copyはステータスでないので、直でprimaryのが良いです

2021-06-02 07:09 UTC, osuke0208 commented on config/status_style.php
> +  'copy' => 'primary'
copyはステータスではないので、不要

2021-06-07 02:09 UTC, ShotaKasaiGit commented on config/status_style.php
> +  'copy' => 'primary'
削除しました

2021-06-07 02:53 UTC, ShotaKasaiGit commented on resources/views/tasks/components/buttons.blade.php
> +  @endif
修正しました

2021-06-07 03:28 UTC, ShotaKasaiGit commented on resources/views/tasks/components/buttons.blade.php
> +    <a href="javascript:void(0)" title="{{__('labels.copy_button')}}" page_form="dialog" page_title="{{$item->title}}" page_url="/tasks/create?copy_id={{$item->id}}&student_id={{$student->id}}" class
$item->target_user->student->id に修正しました

2021-06-07 03:37 UTC, ShotaKasaiGit commented on resources/views/tasks/components/buttons.blade.php
> +    <a href="javascript:void(0)" title="{{__('labels.copy_button')}}" page_form="dialog" page_title="{{$item->title}}" page_url="/tasks/create?copy_id={{$item->id}}&student_id={{$student->id}}" class
直でprimaryに修正しました

2021-06-07 03:37 UTC, ShotaKasaiGit commented on resources/views/students/page/tasks.blade.php
> +@include('dashboard.widget.tasks', ['tasks' => $tasks,'student' => $item])
変数を渡さないよう修正しました

2021-06-07 03:38 UTC, ShotaKasaiGit commented on resources/views/dashboard/widget/tasks.blade.php
> +                  'student' => $student,
リレーションでたどることで変数を渡さないよう修正しました

2021-06-07 03:44 UTC, ShotaKasaiGit commented on resources/views/tasks/components/buttons.blade.php
> +    <a href="javascript:void(0)" title="{{__('labels.copy_button')}}" page_form="dialog" page_title="{{$item->title}}" page_url="/tasks/create?copy_id={{$item->id}}&student_id={{$student->id}}" class
学習記録コピーに修正しました

2021-06-07 04:14 UTC, ShotaKasaiGit commented
一旦ご指摘頂いた部分の修正が完了しました

2021-06-09 02:15 UTC, osuke0208 approved these changes
OKです。
修正ありがとうございました。

2021-06-14 04:52 UTC, merged