#1027 体験一覧に検索機能追加
hachioji-sakura/lms pull request #1037
Opened 2021-06-09 06:35 UTC by ShotaKasaiGit

#1027 のプルリク になります

2021-06-14 05:43 UTC, osuke0208 requested changes

2021-06-14 05:43 UTC, osuke0208 commented on app/Models/Trial.php
> +   });
キーワードをスペース区切りで分割して、クエリを連結するようにしてください。
◆参考
Milestone.php scopeSearchWord()
get_search_word_array()はTraits/Common.phpに定義されています。

2021-06-14 05:43 UTC, osuke0208 commented
1点修正お願いします。

2021-06-15 02:52 UTC, ShotaKasaiGit commented
スペース区切りの修正が完了致しました

2021-06-15 03:47 UTC, osuke0208 approved these changes
OKです。ありがとうございました。

2021-06-15 03:58 UTC, merged