#1033　体験授業の休み連絡に理由の入力をつける
hachioji-sakura/lms pull request #1041
Opened 2021-06-15 01:17 UTC by ShotaKasaiGit

#1033 のプルリク になります

2021-06-17 03:59 UTC, osuke0208 requested changes

2021-06-17 03:59 UTC, osuke0208 commented on resources/views/calendars/simplepage.blade.php
> +              <input type="text" name="rest_result" class="form-control" placeholder="" inputtype="zenkaku">
UserCalendarControllerのl.1022にてrest_reasonをとっているのでnameをrest_reasonに変更してください。

2021-06-18 02:44 UTC, ShotaKasaiGit commented on app/Models/UserCalendarMember.php
> +    }
削除いたしました

2021-06-18 02:44 UTC, ShotaKasaiGit commented
レビューありがとうございます。
ご指摘いただいた箇所の修正が完了致しました

2021-06-18 15:29 UTC, ShotaKasaiGit commented on resources/views/calendars/simplepage.blade.php
> +              <input type="text" name="rest_result" class="form-control" placeholder="" inputtype="zenkaku">
rest_reasonに変更致しました

2021-06-21 08:47 UTC, osuke0208 approved these changes
OKです。ありがとうございました。

2021-06-21 08:47 UTC, merged