Feature/1045 講師のカレンダー確定画面に否認の仕組みを入れる
hachioji-sakura/lms pull request #1053
Opened 2021-06-22 08:39 UTC by ShotaKasaiGit

#1045 のプルリク になります

2021-06-25 02:53 UTC, osuke0208 requested changes
レビューしました。
修正お願いします。

"意図を教えてください"のところは、レスしてもらえれば修正不要かもしれないのでまず書き込みをお願いします。

2021-06-25 02:53 UTC, osuke0208 commented on resources/views/calendars/forms/to_status_form.blade.php
>  @if($item->is_group()==true || ($item->trial_id>0 && $item->is_teaching()==true))
$item->teaching()==trueだけでよさそうに見えます。

グループ授業かどうか、体験授業かどうかを判定する意図を教えてください。

2021-06-25 02:53 UTC, osuke0208 commented on resources/views/calendars/forms/to_status_form.blade.php
> +        {{__('labels.require_student_confirm')}}
キャンセル理由と表示されるように修正

2021-06-25 02:53 UTC, osuke0208 commented on resources/views/calendars/forms/to_status_form.blade.php
> +  <div class="row status_change_form" style="display:none;">
微妙にレイアウトずれしているので、row不要と思います。
scriptの修正が必要であれば合わせてお願いします

2021-06-25 02:53 UTC, osuke0208 commented on resources/views/calendars/forms/to_status_form.blade.php
> +      <textarea id="cancel_reason" name="cancel_reason" class="form-control" placeholder="" inputtype="zenkaku"></textarea>
inputtype="zenkaku"は不要かもしれない
ついていても機能上問題はなさそう

全角の必要性があれば意図を教えてください。

2021-06-25 02:53 UTC, osuke0208 commented on resources/views/calendars/confirm.blade.php
> +        base.pageSettinged("{{$domain}}_member_setting", []);
script内にlaravel変数を埋め込まないほうがよいらしいです。（私もやってしまっている箇所がありますが・・・）

余裕があればhidden等で見えない形で埋め込んだ値をjqueryで読み込むようにしたほうが良いです。

2021-06-25 07:08 UTC, ShotaKasaiGit commented on resources/views/calendars/forms/to_status_form.blade.php
>  @if($item->is_group()==true || ($item->trial_id>0 && $item->is_teaching()==true))
すみません、コピペして残ったままでした

2021-06-25 07:21 UTC, ShotaKasaiGit commented on resources/views/calendars/forms/to_status_form.blade.php
> +        {{__('labels.require_student_confirm')}}
修正しました

2021-06-25 07:36 UTC, ShotaKasaiGit commented on resources/views/calendars/forms/to_status_form.blade.php
> +  <div class="row status_change_form" style="display:none;">
rowの削除をしました

2021-06-25 07:39 UTC, ShotaKasaiGit commented on resources/views/calendars/forms/to_status_form.blade.php
> +      <textarea id="cancel_reason" name="cancel_reason" class="form-control" placeholder="" inputtype="zenkaku"></textarea>
修正しました！

2021-06-25 07:43 UTC, ShotaKasaiGit commented on resources/views/calendars/confirm.blade.php
> +        base.pageSettinged("{{$domain}}_member_setting", []);
一旦上記のみ修正しました

2021-06-25 07:46 UTC, ShotaKasaiGit commented
レビューありがとうございます。
コピペしたままの箇所でしたので、ご指摘頂いたよう修正致しました

2021-06-29 05:24 UTC, osuke0208 commented
OKです。ありがとうございました。

かっこが余分な部分はこちらで修正しました。

2021-06-29 05:24 UTC, merged