幼稚園、小学校、中学校なども読み取るようにする
hachioji-sakura/lms pull request #1054
Opened 2021-06-22 23:18 UTC by engineer-work-take

以下の修正を行いましたので確認お願いいたします。

・Laravelの標準的なコーディングに書き換え
・幼稚園、小学校、中学校、高校、特別学校、看護学校のCSV読み込み追加
・上記をCRUDできるように改変
・テーブルおよびコード内の高校単独とした命名ルールを改める

2021-06-25 02:08 UTC, osuke0208 requested changes
レビューしました。
修正お願いします。

2021-06-25 02:08 UTC, osuke0208 commented on resources/views/schools/component/form/create_form.blade.php
> +        <label>{{$school_view_entity->localizeName('url')}}</label>
__('labels.xxxx')で対応お願いします。

2021-06-25 02:08 UTC, osuke0208 commented on resources/views/schools/component/form/edit_form.blade.php
>  <div id="{{$domain}}_edit">
create_formと共通にしてください。
他ドメインでは$_editのtrue,falseと$itemの存在チェックで出し分けています。

2021-06-28 13:28 UTC, engineer-work-take commented
レビューありがとうございます。
確認いたします。

2021-07-17 14:32 UTC, engineer-work-take commented on resources/views/schools/component/form/create_form.blade.php
> +        <label>{{$school_view_entity->localizeName('url')}}</label>
done

2021-07-17 14:35 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        ];
done

2021-07-17 14:42 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +
done

2021-07-17 15:03 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        $per_page = 25;
done

2021-07-17 15:08 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +
done

2021-07-17 15:09 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        ];
done

2021-07-17 15:11 UTC, engineer-work-take commented on resources/views/schools/component/form/create_form.blade.php
> +        <label>{{$school_view_entity->localizeName('url')}}</label>
done

2021-07-17 15:18 UTC, engineer-work-take commented on app/Models/School.php
> +
done

2021-07-17 15:28 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +
done

2021-07-17 16:57 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        $page_number = $request->page ?? 1;
done

2021-07-17 16:57 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        $items = new LengthAwarePaginator($items, $total_count, $per_page, $page_number, ['path' => $request->url()]);
done

2021-07-17 16:59 UTC, engineer-work-take commented on database/seeds/SchoolSeeder.php
> +<?php
マルチインサートのため、配列指定で直接入れ込みしています

2021-07-17 17:04 UTC, engineer-work-take commented on resources/views/schools/component/form/edit_form.blade.php
>  <div id="{{$domain}}_edit">
安井様との会話の中でフォームをjavascriptを使った切り替え方式にするという話が出たのですが、やり方が分からなかったため、こっちでキャッチアップしたほうが早そうということになりました。

2021-07-18 16:43 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +            $school->save();
done

2021-07-18 16:46 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +            $school_detail->save();
done

2021-07-18 16:50 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +                }
すみません、該当のコメントについて理解が及んでおりません。
申し訳ないですが、具体的なコードなどご教示願えますでしょうか？
よろしくお願いいたします

2021-07-18 17:01 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        $department_list = collect($department_list)->pluck('department', 'id')->all();
done

2021-07-18 17:08 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +            }
削除をmodelに移行しました。
もし認識齟齬ございましたらご指摘いただけると幸いです。
よろしくお願いいたします。

2021-07-18 17:16 UTC, engineer-work-take commented on app/Http/Controllers/SchoolController.php
> +        $res = $this->transaction($request, function () use ($id, $request) {
done

2021-07-18 17:18 UTC, engineer-work-take commented on app/Models/SchoolDetail.php
> +class SchoolDetail extends Model
> リレーションを記載してください。
コードの中で使用している部分を見つけることができませんでした。
こちらどういった内容を記載すればよいでしょうか？

2021-07-19 05:58 UTC, osuke0208 commented on app/Http/Controllers/SchoolController.php
> +            $school_detail->save();
$school->schoolDetail->add($request)に直す

2021-07-19 06:16 UTC, osuke0208 commented on app/Http/Controllers/SchoolController.php
> +                }
下記のようなことを考えていた。
結論は現行コードを採用
ループが減らせるわけでもないため


SchoolとDepartmentにbelongsToManyのリレーションをそれぞれ足す
School.php 
public functoin departments(){return $this->belongsToMany('App\Models\Department')->withPivot('type','created_at','updated_at);}

Department.php 
public function schools(){return $this->belongsToMany('App\Models\School)->withPivot('type','created_at','updated_at);}

SchoolController.php
$school = new School();
$shool->add($request);
$department_ids = 学部idを取得するコード
$school->attach($department_ids);
foreach($school->departments as $department){ $department->pivot->type = "high_school"; $department->save();}

2021-07-19 06:20 UTC, osuke0208 commented on app/Http/Controllers/SchoolController.php
> +            }
SchoolとSchoolDeailの削除は同じid渡して大丈夫か。"school_id" = $school_idではないか？
belongsToManyリレーションを追加したらdetachできるようになる
Schoolにdepartments,Departmentにschoolsリレーション追加

2021-07-19 06:21 UTC, osuke0208 commented on app/Models/SchoolDetail.php
> +class SchoolDetail extends Model
shoolにhasOneがあるので、school_detailにもhasOne追加

2021-07-19 06:26 UTC, osuke0208 commented on database/seeds/SchoolSeeder.php
> +<?php
OK

2021-07-19 06:29 UTC, osuke0208 commented on resources/views/schools/component/form/edit_form.blade.php
>  <div id="{{$domain}}_edit">
OK

2021-07-19 06:33 UTC, osuke0208 commented
今回のコメント部分はこちらで直すので、これで完了です。
ありがとうございました。

2021-07-19 07:45 UTC, osuke0208 commented on app/Http/Controllers/SchoolController.php
> +            $school_detail->save();
修正がDB構造に及ぶのでそのままにする

2021-07-19 07:47 UTC, osuke0208 approved these changes

2021-07-19 07:49 UTC, merged