Feature/1065
hachioji-sakura/lms pull request #1077
Opened 2021-07-08 06:42 UTC by ShotaKasaiGit

#1065 のプルリク になります

2021-07-09 05:29 UTC, osuke0208 requested changes
ルーティングは/students/{id}/textbooksでいいような気がします。
studentsの下に作っているのでstudent_textbooksだとくどいような気がします。

レビューの対応よろしくお願いします。

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +          return "/student_textbooks/".$row['id'];
/textbooks/$row->idでダメでしょうか？

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +              return '/student_textbooks/'.$row['id'].'?action=delete';
使用テキストのcreateフォームにて初期値に使用中のものが入るので、削除フォーム自体が不要かと思われます

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +          return "/student_textbooks/".$row['id'];
もしくは
"link"=>"show"
で対応不可ですかね？

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +          return "/student_textbooks/".$row['id'];
components.listに渡す$domainを"textbooks"にしてしまえば、tableはtextbooksのものとして扱えるので、showにするだけで見えると思います。

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +    ])->with($param);
examsからgrades_eqまでおそらく不要

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +      'items' => $student_textbooks,
"textbooks"　=> $student_textbooks
のが分かりやすいかと思います。

その場合components.listに渡す値も$textbooksに変更

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentTextbookController.php
> +<?php
中間テーブルの操作にあたるので、基本的には不要

削除処理のためだけであればStudentControllerで対応可能です。

2021-07-09 05:29 UTC, osuke0208 commented on app/Models/Student.php
> +  public function store_student_textbooks($form){
引数は$idsとかにしてそのまま渡すほうが良いかと

呼び出し側で$form['textbooks']としたほうが使いやすそうです。

2021-07-09 05:29 UTC, osuke0208 commented on resources/lang/ja/labels.php
> +  'student_textbooks' => '生徒使用テキスト',
enも登録お願いします。

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/components/list_item.blade.php
> +            </a>
あってもよいです。
今回の件はshowで対応できそう

2021-07-09 05:29 UTC, osuke0208 commented on app/Http/Controllers/StudentTextbookController.php
> +<?php
createとstoreで紐づけをする予定と思いますが、
StudentControllerにsync_textbooks_pageとsync_textbooksを追加して、getとpostに割り振れば行けるはず

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/student_textbooks/create.blade.php
> +<div id="school_textbooks" class="direct-chat-msg">
students/以下にディレクトリを切って移設

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/student_textbooks/create_form.blade.php
> +@section('first_form')
students/以下にディレクトリを切って移設

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/student_textbooks/lists.blade.php
> +@section('title')
students/以下にディレクトリを切って移設

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/student_textbooks/paginate.blade.php
> +@if ($paginator->lastPage() > 0)
components.paginateを使いまわせないでしょうか？

2021-07-09 05:29 UTC, osuke0208 commented on resources/views/students/page/student_textbooks.blade.php
> +  {{$domain_name}}試験一覧
誤字

2021-07-09 05:29 UTC, osuke0208 commented on routes/web.php
> +  Route::resource('student_textbooks', 'StudentTextbookController');
student_textbooksのルーティングは不要だと思います。

2021-07-09 05:30 UTC, osuke0208 commented
@hideo-yasui 
このリストページングしたほうがいいですかね？
ほかの生徒関連のタブはページングしてなかったと思います。

2021-07-09 06:40 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +              return '/student_textbooks/'.$row['id'].'?action=delete';
削除のボタンを無くすよう変更しました

2021-07-09 06:40 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +          return "/student_textbooks/".$row['id'];
/textbooks/$row->id　にて対応できました

2021-07-09 06:45 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +    $grades_eq = GeneralAttribute::findKey('grade')->get();
exams、select_exams、subjects、grades　を削除しました。
Subject::get();とGeneralAttributeのGradeは絞り込みのフォームで使いそうなので今のところ残しました。（変数名を$subjects,$gradesに移行しました）

2021-07-09 06:46 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +    ])->with($param);
変数の削除に対応するように、上記returnの変数も削除致しました

2021-07-09 07:00 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +      'items' => $student_textbooks,
"textbooks"　=> $student_textbooks　に修正しました

2021-07-11 07:06 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentTextbookController.php
> +<?php
StudentTextbookControllerを削除しました

2021-07-11 07:15 UTC, ShotaKasaiGit commented on app/Models/Student.php
> +  public function store_student_textbooks($form){
上記のように修正しました

2021-07-11 07:17 UTC, ShotaKasaiGit commented on resources/views/components/list_item.blade.php
> +            </a>
デリートボタン消したので不要ですが残しました

2021-07-11 07:17 UTC, ShotaKasaiGit commented on resources/lang/ja/labels.php
> +  'student_textbooks' => '生徒使用テキスト',
追加しました

2021-07-11 07:52 UTC, ShotaKasaiGit commented on resources/views/student_textbooks/create.blade.php
> +<div id="school_textbooks" class="direct-chat-msg">
移設しました

2021-07-11 07:53 UTC, ShotaKasaiGit commented on resources/views/student_textbooks/create_form.blade.php
> +@section('first_form')
移設しました

2021-07-11 07:53 UTC, ShotaKasaiGit commented on resources/views/student_textbooks/lists.blade.php
> +@section('title')
移設しました

2021-07-11 07:53 UTC, ShotaKasaiGit commented on resources/views/student_textbooks/paginate.blade.php
> +@if ($paginator->lastPage() > 0)
移設しました

2021-07-11 07:56 UTC, ShotaKasaiGit commented on routes/web.php
> +  Route::resource('student_textbooks', 'StudentTextbookController');
削除しました

2021-07-11 07:58 UTC, ShotaKasaiGit commented on resources/views/students/page/student_textbooks.blade.php
> +  {{$domain_name}}試験一覧
修正しました

2021-07-12 07:33 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +    $grades_eq = GeneralAttribute::findKey('grade')->get();
OK

2021-07-12 07:34 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +          return "/student_textbooks/".$row['id'];
OK

2021-07-12 07:34 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +              return '/student_textbooks/'.$row['id'].'?action=delete';
OK

2021-07-12 07:34 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +    ])->with($param);
OK

2021-07-12 07:35 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +      'items' => $student_textbooks,
OK

2021-07-12 07:38 UTC, osuke0208 commented on app/Http/Controllers/StudentTextbookController.php
> +<?php
pullして確認したところまだ残っているよう出す。
push忘れかな？

2021-07-12 07:39 UTC, osuke0208 commented on app/Models/Student.php
> +  public function store_student_textbooks($form){
OK

2021-07-12 07:39 UTC, osuke0208 commented on resources/lang/ja/labels.php
> +  'student_textbooks' => '生徒使用テキスト',
OK

2021-07-12 07:39 UTC, osuke0208 commented on resources/views/components/list_item.blade.php
> +            </a>
OK
不都合があるようだったら、ほかの修正に合わせてこちらで消します。

2021-07-12 07:40 UTC, osuke0208 commented on resources/views/student_textbooks/create.blade.php
> +<div id="school_textbooks" class="direct-chat-msg">
OK

2021-07-12 07:40 UTC, osuke0208 commented on resources/views/student_textbooks/create_form.blade.php
> +@section('first_form')
OK

2021-07-12 07:41 UTC, osuke0208 commented on resources/views/student_textbooks/lists.blade.php
> +@section('title')
OK

2021-07-12 07:43 UTC, osuke0208 commented on resources/views/student_textbooks/paginate.blade.php
> +@if ($paginator->lastPage() > 0)
意図が伝わっていなかったようです。すみません。
students.textbooks.paginate.blade.php
↓
components.paginate.blade.php

で置き換えると不都合がでますか？

2021-07-12 07:43 UTC, osuke0208 commented on resources/views/students/page/student_textbooks.blade.php
> +  {{$domain_name}}試験一覧
OK

2021-07-12 07:44 UTC, osuke0208 commented on routes/web.php
> +  Route::resource('student_textbooks', 'StudentTextbookController');
OK

2021-07-12 07:45 UTC, osuke0208 commented
@ShotaKasaiGit 
Resolveしてないコメントについて確認お願いします。

2021-07-12 08:00 UTC, osuke0208 commented
今回の変更部分ではないのですが、

1．契約者でログイン　→　生徒情報　→　使用テキスト登録
→POSTで403エラー

2．契約者でログイン　→生徒情報　→　テキスト名クリック
→システムエラー
 TextbookControllerのl.270$user->is_accessで落ちている

のような現象を確認しています。

ユーザ誰であっても生徒所有テキストを変更できるように調整をお願いします。

2021-07-13 13:17 UTC, ShotaKasaiGit commented on resources/views/student_textbooks/paginate.blade.php
> +@if ($paginator->lastPage() > 0)
components.paginate.blade.phpに置き換えるよう修正しました。
こちらで勘違いがありました。

2021-07-13 14:38 UTC, ShotaKasaiGit commented
レビューありがとうございます！
Resolveしていないものと、403の修正が完了しました

2021-07-14 08:08 UTC, osuke0208 commented on resources/views/student_textbooks/paginate.blade.php
> +@if ($paginator->lastPage() > 0)
OK

2021-07-14 08:10 UTC, osuke0208 approved these changes

2021-07-14 08:11 UTC, osuke0208 commented
OKです。ありがとうございました。

2021-07-15 07:10 UTC, merged