Feature/888
hachioji-sakura/lms pull request #1095
Opened 2021-07-19 06:05 UTC by ShotaKasaiGit

#888 のプルリク になります

2021-07-19 09:00 UTC, osuke0208 commented on app/Console/Commands/DailyProcCommand.php
> +    $teachers =Teacher::notApprovedTeachers()->get();
引数を追加する予定なので、現在から見て前月の月初日と月末日を指定してください。
scope側で初期値の指定はありますが、明示的にやっておいてください。

2021-07-19 09:01 UTC, osuke0208 commented on app/Models/Teacher.php
> +  public function scopeNotApprovedTeachers($query){
$from_dateも$to_dateも引数で指定がないときnullにしてemptyならば、前月の結果が出るように変数のセットロジックを追加してください。

2021-07-28 03:22 UTC, ShotaKasaiGit commented on app/Models/Teacher.php
> +        return $query->where('status', "fix")
修正しました

2021-07-28 06:19 UTC, ShotaKasaiGit commented on app/Models/Teacher.php
> +  public function scopeNotApprovedTeachers($query){
追加しました

2021-07-28 06:31 UTC, ShotaKasaiGit commented on app/Console/Commands/DailyProcCommand.php
> +    $teachers =Teacher::notApprovedTeachers()->get();
修正しました

2021-07-28 07:30 UTC, ShotaKasaiGit commented on resources/views/teachers/tiles.blade.php
> +        <input type="checkbox" value="1" name="not_approved" class="icheck flat-green"
修正しました

2021-07-28 07:42 UTC, ShotaKasaiGit commented
遅くなりもうしわけないです。修正が完了しました

2021-07-29 07:19 UTC, osuke0208 commented on app/Http/Controllers/StudentController.php
> +      $items->notApprovedTeachers($request->search_subject);
引数が日付で2つでは？

2021-07-29 07:33 UTC, osuke0208 commented on app/Models/Teacher.php
> +            ->orWhereNull('checked_at');
講師絞り込みでチェックしてみると、6月の未承認講師にかなりの人数が出てきす。
checked_at周りの絞り込みにステータスを足す必要がありそうです。
こちらでも安井さんと調査します。

2021-07-29 07:35 UTC, osuke0208 requested changes
月末承認についてはこちらでの確認があるので、少々お待ちください。
引数の修正だけお願いします。

2021-07-30 08:47 UTC, osuke0208 commented on app/Models/Teacher.php
> +            ->orWhereNull('checked_at');
presence
absence
rest
lecture_cancel
の時にchecked_at=nullなら未承認で条件を直してください。

2021-07-30 08:49 UTC, osuke0208 commented on app/Models/Teacher.php
> +            ->orWhereNull('checked_at');
where句で書くと以下になります。

status = "fix" or ( status in (上の奴ら) and checked_at is null)

2021-08-02 07:35 UTC, osuke0208 commented
>月末承認についてはこちらでの確認があるので、少々お待ちください。
引数の修正だけお願いします。
こちらの確認が取れましたので、コメントの通りに修正お願いします。

2021-08-05 02:11 UTC, ShotaKasaiGit commented on app/Models/Teacher.php
> +            ->orWhereNull('checked_at');
条件を修正しました

2021-08-05 02:11 UTC, ShotaKasaiGit commented on app/Http/Controllers/StudentController.php
> +      $items->notApprovedTeachers($request->search_subject);
修正しました

2021-08-05 02:13 UTC, ShotaKasaiGit commented
8/5 
レビューありがとうございました。
修正が完了しました。

2021-08-10 01:52 UTC, osuke0208 commented
修正ありがとうございました。

2021-08-10 01:53 UTC, osuke0208 commented
設計時の考慮もれ

・期間講習の演習season_trainingがfixで残るため、それを持っていると対象になってしまう

2021-08-14 05:08 UTC, osuke0208 commented
修正ありがとうございました。
コードはこれでOKだと思います。

2021-08-14 06:51 UTC, merged