Feature/1155
hachioji-sakura/lms pull request #1175
Opened 2021-08-30 11:23 UTC by ShotaKasaiGit

#1155 のプルリク になります

2021-09-06 03:01 UTC, osuke0208 commented
追加授業をオンラインで作成して動作確認したところ、calendars.fixではなくcalendars.simplepageを参照しているようです。
契約者による予定確認はfix前提なので、calendars.fixにはいかなさそうですね。

こちらのページを参照するケースがあれば教えてください。

該当部分のUserCalendarControllerのコードスクショ貼っときます
![image](https://user-images.githubusercontent.com/61462583/132154644-0bafc0cc-cb72-448b-8357-8af678f91711.png)

2021-09-06 03:04 UTC, osuke0208 commented
生徒詳細の通塾設定のほうはOKです

2021-09-18 03:58 UTC, ShotaKasaiGit commented
レビューありがとうございます。
calendars.fixの件ですが、

カレンダーを作成 -> 講師詳細から予定を確定する( 生徒の確認を必要とする)
 ->  生徒詳細から予定を確認するボタン押下
の操作時に、calendars.fix にてskypeidの確認をしていると認識しています

2021-09-18 04:02 UTC, ShotaKasaiGit commented
<img width="1370" alt="85c271de9a071138779bfaa4bfcabfbe" src="https://user-images.githubusercontent.com/65011529/133871860-1bae7824-fd6c-4fa1-9f33-44dd002f7e8e.png">

2021-09-18 06:15 UTC, osuke0208 commented
了解しました。

calendars.fixの修正による変更箇所は確認できました。
こちらはOKですし、必要な修正でした。

私が指摘した個所は
カレンダーを作成 -> 講師詳細から予定を確定する( 生徒の確認を必要とする)
の後に
メール履歴を開く->契約者へのメールからURLをコピーして別ブラウザで開く
という動作をしたときに出る確定のページのほうでした。

こちらも合わせて修正をお願いします。

2021-09-18 06:16 UTC, osuke0208 commented
![image](https://user-images.githubusercontent.com/61462583/133878411-a2424c41-37c8-45e3-bed6-1654c7ba1324.png)

2021-09-18 06:18 UTC, osuke0208 commented
カレンダーを契約者が確認する場合、メールからジャンプするケースが多いと思われるので合わせて修正が必要です。

2021-09-23 12:04 UTC, ShotaKasaiGit commented
ご指摘いただいた箇所の作業が完了しました

2021-09-24 01:12 UTC, osuke0208 requested changes
URLからアクセスするパターンのほうで、もう一声修正をお願いします。
私の説明不足で申し訳ありませんでした。

2021-09-24 01:12 UTC, osuke0208 commented on resources/views/calendars/simplepage.blade.php
> +                <i class="icon fa fa-exclamation-triangle"></i>{!!nl2br(__('messages.error_skype_name_not_found_student'))!!}
オンラインで体験授業をする場合、ログインして設定することができないケースがあります。
この場合issueにもある通り、保存を同時に行う必要があります。

ですので、teachers.forms.skype_nameを追加で表示して、まとめてpostしてください。
その後、Controllerで受け取ったときskype_nameがあれば、対象生徒に追加するような変更もお願いします。

2021-09-29 15:25 UTC, ShotaKasaiGit commented
修正が完了しました！
よろしくお願いします。

2021-10-01 03:25 UTC, osuke0208 approved these changes
OKです。ありがとうございました。

2021-10-01 03:25 UTC, merged